### ISSUE TITLE
Create basic Spring Boot webapp template for app (200pts)

### ISSUE THREAD

**Issue by sassanhashemi** [ucsb-cs56-f18/ucsb-cs56-goodsleepalarm#1]

**Comment by fzhao06** [comment]
The home page will be the sleep / wake-up times calculated.
There will be another page for inputting events/times and user settings (maybe split into two pages).
The first item on the nav-bar should be the home page, then events/times, then maybe user settings if needed.
In the upper right there will be two text boxes for the username / password and room for displaying an invalid username / password.
At minimum this webapp template will show the general organization/layout of these pages, as the pages will be implemented when closing other issues.

**Comment by rphammy** [comment]
Mentor Approved

**Comment by shao158** [comment]
Congratulation! 
200 points are awarded!
