### ISSUE TITLE
JUnit/Jacoco Testing for SleepWakeAlgorithm

### ISSUE THREAD

**Issue by fzhao06** [ucsb-cs56-f18/ucsb-cs56-goodsleepalarm#10]
Write tests to help check for any errors in the SleepWakeAlgorithm function calcTime using JUnit tests. Also set up jacoco test coverage to check if tests aren't extensive enough.

**Comment by shao158** [comment]
200 points awarded. Congrats! 

The only suggestion is that, for each test case, you might want to add comments explaining why it is necessary, what it is testing, and etc., which is important.
