### ISSUE TITLE
Create a webpage for the user to input current schedule

### ISSUE THREAD

**Issue by sassanhashemi** [ucsb-cs56-f18/ucsb-cs56-goodsleepalarm#2]

**Comment by fzhao06** [comment]
Page should accept events and times, which when entered will update the wake up time.
On this page or perhaps some settings page user preferences can be modified (length of sleep, ideal wake-up time / sleep time, etc.).
Info here may be stored into some database for user settings/schedules.

**Comment by rphammy** [comment]
Is this a separate page from your issue called "Allow user to make changes to their profile/schedule" ? if so then specify. If not, then merge the issues
