### ISSUE TITLE
Create algorithm to find sleep and wake time given time of next day's first event (100pts)

### ISSUE THREAD

**Issue by sassanhashemi** [ucsb-cs56-f18/ucsb-cs56-goodsleepalarm#4]

**Comment by fzhao06** [comment]
Write Java code that returns the times to sleep and wake up for the given first event of the next day.
Length of sleep and ideal wake-up time should be variables that default respectively to 8 hours and 1 hours before the first event of the day.
This algorithm should be run everyday/when events are modified/added/removed and on user login.

**Comment by rphammy** [comment]
Mentor Approved
