### ISSUE TITLE
Allow user to make changes to their profile/schedule

### ISSUE THREAD

**Issue by junayednaushad** [ucsb-cs56-f18/ucsb-cs56-goodsleepalarm#7]
- [ ] user can add or modify current schedule by manually changing the times for events on their schedule or by inputting their google calendar 

- [ ] user can modify sleep preferences (ex: change preference from waking 1 hour before first event to waking 2 hours before first event)

- [ ] user can enter their feedback (ex: user can specify that the sleep schedule being generated is not feasible to follow on certain days so the recommendation can make necessary adjustments)

- [ ] user can enter a day outside of their usual schedule on which they have to wake up or go to sleep at a different time and the app will generate a sleep/wake time just for that day

**Comment by rphammy** [comment]
Will this all of these options be available on one page in your webapp? Specify

**Comment by junayednaushad** [comment]
The options will appear as tabs on the web app after the user logs in. Each tab will take the user to a new page.

**Comment by rphammy** [comment]
Mentor Approved
