### ISSUE TITLE
Create a login/signin page (200pts)

### ISSUE THREAD

**Issue by fzhao06** [ucsb-cs56-f18/ucsb-cs56-goodsleepalarm#8]
There will be two text boxes on the nav bar in the upper right corner that allow the entry of a username and password.
This entry will be given to the backend to validate through the database.
If the entry is invalid the nav bar will display an error next to the text boxes and allow a retry.
Else the page will change to the home page and login the user with their user profile settings loaded.

**Comment by rphammy** [comment]
Mentor Approved

**Comment by fzhao06** [comment]
https://github.com/ucsb-cs56-webapps/ucsb-cs56-goodsleepalarm/pull/4
